# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fe2ce658d15f7031296b7b064d2f27cf03610790e2e78b74109e0443790c98a88ba1fd08e90387ad20f7dacb3976b6d00c9c82826e0431c7b1987606a3b885d

test:
  secret_key_base: 89f920e3ae36cbcb78d5c32a977a19b3ca5d9cee914c3c301a4d1a6bfa0839f4010d9b3524b0935d55f81f7db49f42f5d39bd76ba1fd06aace796912c8f8826c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
